## Main Ansible playbook that will call all the tests
---

- name: Mef_eLine Tests
  hosts: localhost

  tasks:
    - name: Install SSHPASS on CentOS
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/sshpass-1.06-2.el7.x86_64.rpm
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install SSHPASS on Ubuntu
      apt:
        name: sshpass
        state: present
      when: ansible_distribution == 'Ubuntu'

#    - name: Install Python
#      include_role:
#        name: python


- name: The Roles
  hosts: all
  tasks:
    - name: Start the Test 1 Roles
      command: ansible-playbook tests.yml

    - name: Delete SSHPASS on CentOS
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/sshpass-1.06-2.el7.x86_64.rpm
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Delete SSHPASS on Ubuntu
      apt:
        name: sshpass
        state: present
      when: ansible_distribution == 'Ubuntu'
