## Main Ansible playbook that will call all Roles
---
#- name: Test Connection to Hosts
#  hosts: all
#  pre_tasks:
#    - name: Generate KEY
#      openssh_keypair:
#        path: /tmp/id_ssh_rsa
#        force: True
#
#    - name: Add KEY to Hosts
#      authorized_key:
#        state: present
#        key: "{{ lookup('file', 'id_rsa.pub') }}"
#        path: /tmp/id_ssh_rsa
#
#  tasks:
#    - name: Ping the Hosts
#      ping:

- name: Create VLANs
  hosts: all:!localhost
  tasks:
    - name: Start Role create_vlan
      include_role:
        name: create_vlan

- name: Start Role create_evc
  hosts: localhost
  tasks:
    - name: Start Role Create EVCs
      include_role:
        name: create_evc

- name: Start Test_One
  hosts: all:!localhost
  tasks:
    - name: Start Role test_one
      include_role:
        name: test_one

- name: Delete EVCs
  hosts: localhost
  tasks:
    - name: Start Role delete_evc
      include_role:
        name: delete_evc

- name: Delete VLan
  hosts: all:!localhost
  tasks:
    - name: Start Role delete_vlan
      include_role:
        name: delete_vlan

    - name: Start Role cleaning
      include_role:
        name: cleaning

#- name: Delete Keys
#  hosts: all
#  tasks:
#    - name: Delete KEY from Hosts
#      authorized_key:
#        state: absent
#        key: "{{ lookup('file', 'id_rsa.pub') }}"
#        path: /tmp/id_ssh_rsa

