---
- name: Copy EVC Scrip
  copy:
    src: "{{ role_path }}/files/evc_request.py"
    dest: /tmp/evc_request.py

- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
