---
- name: Running create EVC Script
  shell: role/create_evc/files/evc_request.py {{ controller_addr }} {{ controller_port }} {{ item }} create_evc
  args:
    chdir: /tmp/
    executable: python3
  with_sequence: start="{{ start}}" end="{{ end }}"