---
- name: Running delete EVC Script
  shell: "python 3 evc_request.py {{ controller_addr }} {{ controller_port }} {{ item }} delete_evc"
  args:
    chdir: /tmp/
    removes: circuits.txt
  with_sequence: start="{{ start|int }}" end="{{ end|int }}"