---
- name: Install vconfig (without 'args').
  command: yum install vconfig.x86_64


- name: Create VLANs on CentOS
  command: vconfig add {{net}} {{item}} up
  with_sequence: start="{{ start|int }}" end="{{ end|int }}"

- name: Config VLANs on CentOS
  command: ifconfig {{net}}.{{item}} 10.0.{{item}}.{{inet}}/24 up
  with_sequence: start="{{ start|int }}" end="{{ end|int }}"
