---
- name: Removed VLANs
  shell: vconfig rem {{net}}.{{item}}
  ignore_errors: yes
  with_sequence: start="{{ start|int }}" end="{{ end|int }}"

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
